import "./globals.css";
import VideoBackground from "@/components/VideoBackground";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const VideoBackground = dynamic(() => import("./components/VideoBackground"), { ssr: false });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-neuro">
        <div className="relative bg-black w-full h-full min-h-svh overflow-hidden">
          <VideoBackground />
          <main className="relative z-10">{children}</main>
        </div>
      </body>
    </html>
  );
}
